Add constrain methods to UILayoutGuide
mooncascade/MoonKit pull request #8
Opened 2022-08-12 04:35 UTC by mc-vladyslav-kupriienko

## Context

This PR adds the `constrain` methods to `UILayoutGuide`. 

This might be useful for scroll views for example, where we sometimes have to operate on `contentLayoutGuide` and `frameLayoutGuide`.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation including README.md
- [x] My changes generate no new warnings
- [x] My changes generate no breaking changes

2022-08-12 06:46 UTC, mc-aleksander-stos approved these changes

2022-08-12 08:18 UTC, kuldar-daniel requested changes

2022-08-12 08:18 UTC, kuldar-daniel commented on Sources/MoonPresentation/LayoutConstraints/UIView+Constrainable.swift
> +internal extension NSLayoutConstraint.Edge {
I think it would now make sense to move these extensions into separate files.

2022-08-12 08:18 UTC, kuldar-daniel commented on Sources/MoonPresentation/LayoutConstraints/UIView+Constrainable.swift
> +internal extension NSLayoutConstraint.Dimension {
Same as above.

2022-08-12 08:18 UTC, kuldar-daniel commented on Sources/MoonPresentation/LayoutConstraints/UIView+Constrainable.swift
> +internal extension NSLayoutConstraint.Axis {
Same as above.

2022-08-12 08:18 UTC, kuldar-daniel commented on Sources/MoonPresentation/LayoutConstraints/UIView+Constrainable.swift
> +internal extension CGFloat {
Same as above.

2022-08-12 08:18 UTC, kuldar-daniel commented on Sources/MoonPresentation/LayoutConstraints/UIView+Constrainable.swift
> +internal extension UIEdgeInsets {
Same as above.

2022-08-15 14:49 UTC, mc-anton-karpov approved these changes

2022-08-23 00:06 UTC, mc-vladyslav-kupriienko commented
I have moved the `NSLayoutConstraint.*` and other related extensions to a separate file.

I also ran SwiftFormat and SwiftLint on the package and fixed the warnings. I feel like it would make sense for our toolkit to follow our own SF/SL rules. I am torn on whether I should put it as a separate PR or just add to this one. Would love to hear your opinions!

2022-08-23 06:05 UTC, mc-karina-karimova approved these changes

2022-08-30 03:27 UTC, merged